services:
  auth_service:
    build:
      context: ./auth_service
    env_file: ./auth_service/.env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  bot_service:
    build:
      context: ./bot_service
    env_file: ./bot_service/.env
    ports:
      - "8001:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
      - rabbitmq

  bot_polling:
    build:
      context: ./bot_service
    env_file: ./bot_service/.env
    command: python -m app.bot.run_polling

  celery_worker:
    build:
      context: ./bot_service
    env_file: ./bot_service/.env
    command: celery -A app.infra.celery_app.celery_app worker --loglevel=info

  rabbitmq:
    image: rabbitmq:3.11-management

  redis:
    image: redis:7-alpine