[pytest]

# Добавляет корень проекта в PYTHONPATH
# Позволяет импортировать app.*
pythonpath = .

# Автоматическая поддержка async тестов
asyncio_mode = auto

# Отключение лишних warning сообщений
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning